### ISSUE TITLE
Error on task ansible-omdistro | template hosts.mk

### ISSUE THREAD

**Issue by mikerj1** [sfromm/ansible-omdistro#1]
Hello - I've been unable to get this to work with either ansible 1.9 or 2.1.  Is this still a functional role with these versions? 

Error message in 1.9:

fatal: [ocdlog] => {'msg': "AnsibleError: file: /Users/mikerjohnson/Documents/repos/instantdx/idx-ansible/roles/ansible-omdistro/templates/hosts.mk.j2, line number: 11, error: Encountered unknown tag 'do'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.", 'failed': True}
fatal: [ocdlog] => {'msg': "AnsibleError: file: /Users/mikerjohnson/Documents/repos/instantdx/idx-ansible/roles/ansible-omdistro/templates/hosts.mk.j2, line number: 11, error: Encountered unknown tag 'do'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.", 'failed': True}

FATAL: all hosts have already failed -- aborting

Basically the same thing in 2.1.

TASK [ansible-omdistro : template hosts.mk] ************************************
fatal: [ocdlog]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleError: template error while templating string: Encountered unknown tag 'do'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.. String: # -*- mode: python -*-\n# {{ansible_managed}}\n\nall_hosts = [\n{% if omdistro_use_inventory %}\n# ansible inventory\n{% for host in groups['all'] %}\n{%     set grps = ['snmp', 'tcp'] %}\n{%     for grp in group_names %}\n{%         if grp in omdistro_hostgroups %}\n{%             do grps.append(grp) %}\n{%         endif %}\n{%     endfor %}\n    \"{{ host }}|{{ grps|join('|') }}\",\n{% endfor %}\n{% endif %}\n#\n# netmon inventory\n# check_mk can only 'discover' ipv4\n{% for host in netmon.devices %}\n    \"{{ host.name }}|{{ host.groups|join('|') }}\",\n{% endfor %}\n]\n\n{% if not omdistro_scan_parents %}\n# parent definitions\nparents += [\n{% for host in netmon.devices %}\n{%     if host['ext'] is defined and host['ext']['omdistro'] is defined and  host['ext']['omdistro']['parent'] is defined %}\n{%         if host['ext']['omdistro']['parent'] is string %}\n    (\"{{ host.ext.omdistro.parent }}\", [\"{{ host.name }}\"]),\n{%         else %}\n{%             for p in host['ext']['omdistro']['parent'] %}\n    (\"{{ p }}\", [\"{{ host.name }}\"]),\n{%             endfor %}\n    (\"{{ host.ext.omdistro.parent }}\", [\"{{ host.name }}\"]),\n{%         endif %}\n{%     endif %}\n{% endfor %}\n]\n{% endif %}\n"}

Thanks

**Comment by sfromm** [comment]
My apologies for the late reply.  This repository is no longer maintained.  

For this specifically, it looks like I was using the following jinja extensions in the template:  `jinja2.ext.loopcontrols,jinja2.ext.do`.  I suggest giving that a try.  Good luck!
